drop database if exists PRUEBAS;
CREATE DATABASE PRUEBAS;

	USE PRUEBAS;
	 CREATE TABLE RESERVA(
	 	NOMBRE VARCHAR (20) ,
	    APELLIDO VARCHAR(20) ,
	    FECHA_RESERVACION DATE ,
	    HORA TIME ,
	    EVENTO VARCHAR(100) ,
	    VEHICULO VARCHAR(50),
	    RESIDENCIA VARCHAR(50),
	    CODIGO_RESERVA INT PRIMARY KEY AUTO_INCREMENT
	 );


	 CREATE TABLE USUARIOS_PASS(
	 	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	 	PASSWORD VARCHAR(20),
	 	USUARIOS VARCHAR(50)
	 	);


	CREATE TABLE USUARIOS_RESERVA(
		ID INT,
		FOREIGN KEY (ID) REFERENCES USUARIOS_PASS(ID),
		CODIGO_RESERVA INT,
		FOREIGN KEY (CODIGO_RESERVA) REFERENCES RESERVA(CODIGO_RESERVA)

	);




	